### ISSUE TITLE
"modulus operator.png" is wrong

### ISSUE THREAD

**Issue by rioj7** [RickSekuloski/rick-javascript-book1#1]
Image `modulus operator.png` is wrong.

It is not the modulo operator but the remainder operator.

It uses a variable `q` with "unknown" value.

What it should have been is

```
// the remainder operator (%) returns the division remainder.
let g = 5;
let w = 2;
let r = g % w;
console.log(r);
```

What the example image is calculating is: ` (5 / 2) % 2 == 0.5`

In JavaScript

```
5 % 2 == 1
2.5 % 2 = 0.5
```

**Comment by RickSekuloski** [comment]
Edited: the updated version is available now! Please check.
Original message:

Hi there rioj7,
yes that is my mistake and thank you for pointing out. The book is updated just as I'm writing this post. You will see the changes in the next day or so.
Thank you so much.
I'm sorry for any inconvenience caused.
Please let me know if you see the changes.
Rick

**Comment by RickSekuloski** [comment]
I have edited as requested
