### ISSUE TITLE
Typo: "Caclulate" in many images and lecture5 source code

### ISSUE THREAD

**Issue by rioj7** [RickSekuloski/rick-javascript-book1#2]
Subject says it all

**Comment by RickSekuloski** [comment]
***********Updated***********
You will see all of the changes latter today. Thank you again for letting me know.
Stay safe.
***********Original Message***********
I should hire you as proofreader as the others I hired didn't spotted those. They will be fixed asap. Thank you

**Comment by RickSekuloski** [comment]
I have edited as requested
